input {
      stdin {
       }
      jdbc {
        jdbc_connection_string => "jdbc:mysql://localhost:3306/taptap?characterEncoding=UTF-8&useSSL=false&autoReconnect=true"
        jdbc_user => "root"
        jdbc_password => "root"
       jdbc_driver_library => "D:\Data_acquisition\mysql/mysql-connector-java-5.1.38.jar"
       jdbc_driver_class => "com.mysql.jdbc.Driver"
       jdbc_default_timezone =>"Asia/Shanghai"
       statement =>"SELECT * FROM android300"
     }
 }


output {
    elasticsearch {
        hosts => ["127.0.0.1:9200"]
        index => "android_hotplayed_index"
        document_type =>"android_hotplayed_type"
        template_overwrite => true
    }
    stdout {
        codec => "rubydebug"
    }
}